# Generated by Django 5.2.8 on 2026-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الخصم')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'قيمة ثابتة')], default='percentage', max_length=10, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الخصم')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للشراء')),
                ('valid_from', models.DateTimeField(verbose_name='صالح من')),
                ('valid_to', models.DateTimeField(verbose_name='صالح حتى')),
                ('max_usage', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
            },
        ),
    ]
