# Generated by Django 6.0 on 2026-01-01 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'تم التأكيد'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'تم الاسترجاع')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_method', models.CharField(choices=[('cash', 'الدفع عند الاستلام'), ('card', 'بطاقة ائتمان'), ('bank', 'تحويل بنكي')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.BooleanField(default=False, verbose_name='حالة الدفع')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع الفرعي')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='رسوم الشحن')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المجموع النهائي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('is_default', models.BooleanField(default=False, verbose_name='العنوان الافتراضي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عنوان الشحن',
                'verbose_name_plural': 'عناوين الشحن',
            },
        ),
    ]
